# Generated by Django 3.2 on 2024-01-24 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0089_remove_container_bill_commission'),
    ]

    operations = [
        migrations.AddField(
            model_name='container',
            name='bill_commission',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
    ]
