# Generated by Django 3.2 on 2024-01-25 00:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0094_auto_20240125_0146'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='container',
            name='bill_commission',
        ),
        migrations.RemoveField(
            model_name='container',
            name='main_commission',
        ),
    ]
