# Generated by Django 3.2 on 2024-01-28 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0095_auto_20240125_0207'),
    ]

    operations = [
        migrations.AddField(
            model_name='container',
            name='bill_commission',
            field=models.DecimalField(blank=True, decimal_places=2, editable=False, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='container',
            name='main_commission',
            field=models.DecimalField(blank=True, decimal_places=2, editable=False, max_digits=10, null=True),
        ),
    ]
